# Generated by Django 5.2.12 on 2026-03-24 02:13

import django.db.models.deletion
import wagtail.fields
import wagtailmetadata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_search_image'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', models.CharField(default='About Us', max_length=255)),
                ('intro', models.TextField(blank=True)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('mission_heading', models.CharField(blank=True, max_length=255)),
                ('mission_text', models.TextField(blank=True)),
                ('vision_heading', models.CharField(blank=True, max_length=255)),
                ('vision_text', models.TextField(blank=True)),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtailmetadata.models.WagtailImageMetadataMixin, 'wagtailcore.page', models.Model),
        ),
    ]
